import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { NextFont } from 'next/dist/compiled/@next/font';
import NavBar from "@/components/NavBar";

const satoshi: NextFont = localFont({
    src: [
        {
            path: '../public/fonts/Satoshi-Variable.ttf',
            style: 'normal',
        },
        {
            path: '../public/fonts/Satoshi-VariableItalic.ttf',
            style: 'italic',
        },
    ],
    variable: '--font-satoshi',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' data-theme='masskooramy'>
            <body className={satoshi.className}>
            <NavBar/>
            {children}
            </body>
        </html>
    );
}
